Next try

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,16 +9,11 @@ on:
       - main
 
 jobs:
-  test:
+  test-linux:
     strategy:
       matrix:
         java: ['11', '21']
-        os: [ubuntu-latest, macos-latest, windows-latest]
-        exclude:
-          - os: macos-latest
-            java: '21'
-          - os: windows-latest
-            java: '21'
+        os: [ubuntu-latest]
     runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v3
@@ -38,6 +33,62 @@ jobs:
           EOM
           sha256sum --check sha.txt
           tar xvf d2-v0.7.0-linux-amd64.tar.gz
+          cp d2-v0.7.0/bin/d2 /usr/local/bin
+      - name: Build
+        run: |
+          ./gradlew check
+  test-windows:
+    strategy:
+      matrix:
+        java: ['11']
+        os: [windows-latest]
+    runs-on: ${{ matrix.os }}
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: ${{ matrix.java }}
+      - name: Install d2
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          # The script should fail if sha256sum --check fails
+          set -e
+          gh release download v0.7.0 --repo terrastruct/d2 --pattern d2-v0.7.0-windows-amd64.tar.gz
+          cat > sha.txt <<EOM
+          4aded6f6b1576ab77eb9ff6051254bec42620dd4a5af57fb02e7619f06660ff6  d2-v0.7.0-windows-amd64.tar.gz
+          EOM
+          sha256sum --check sha.txt
+          tar xvf d2-v0.7.0-windows-amd64.tar.gz
+          cp d2-v0.7.0/bin/d2 /usr/local/bin
+      - name: Build
+        run: |
+          ./gradlew check
+  test-mac:
+    strategy:
+      matrix:
+        java: ['11']
+        os: [macos-latest]
+    runs-on: ${{ matrix.os }}
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: ${{ matrix.java }}
+      - name: Install d2
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          # The script should fail if sha256sum --check fails
+          set -e
+          gh release download v0.7.0 --repo terrastruct/d2 --pattern d2-v0.7.0-macos-arm64.tar.gz
+          cat > sha.txt <<EOM
+          7d8b3b5900d5609882d1a98fbb5c5a349332a706e0ef063b6db4aebdef09d274  d2-v0.7.0-macos-arm64.tar.gz
+          EOM
+          shasum -a 256 --check sha.txt
+          tar xvf d2-v0.7.0-macos-arm64.tar.gz
           cp d2-v0.7.0/bin/d2 /usr/local/bin
       - name: Build
         run: |
